services:
  db:
    ports:
      - "3306:3306"

  api:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules

  web:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
      - /app/.next
      - /app/node_modules

  nginx:

volumes:

networks:
